spring:
  application:
    name: 

  datasource:
    url: 
    username: 
    password: 

  jpa:
    hibernate:
      ddl-auto: 
    database-platform: 

eureka:
  client:
    serviceUrl:
      defaultZone:

server:
  port: 
