spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://localhost:5432/FitGenie_db
    username: postgres
    password: 1202sonagarvish

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080